### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by noerw** [seletskiy/godiff#4]
Can you clarify under what license this code is provided?
Thanks

**Comment by imrejonk** [comment]
I would like to know this as well. There's a bit of legal concern in projects that use your godiff code at the moment:

https://gitea.com/gitea/tea/issues/492
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14129
https://bugs.archlinux.org/task/75663
https://artemis.sh/2022/08/21/this-program-is-illegally-packaged-in-14-distributions.html
https://news.ycombinator.com/item?id=32546461

**Comment by samboy** [comment]
It hasn’t been updated for six years. I think the only solution is to rewrite it with an open source license.

For the record, I have had multiple successful cases where, with some package I found in the Internet which I liked but had an unclear license, contacting the author and copyright owner and getting the package relicensed under something open source compatible. I personally dual license my projects as Unlicense or BSD0 (since Google doesn’t like the Unlicense but will accept the BSD0 one) to make the licensing as permissive as possible.

**Comment by kovetskiy** [comment]
Hey guys, I know the author personally and asked him to add a license.

**Comment by seletskiy** [comment]
@kovetskiy Thanks.

The license issue is a little exaggerated.
I never imagined anyone would find use for that code.
And two years ago, the original issue was plainly lost in a never-ending stream of notifications.
By contacting me directly using my profile's email address, the problem could be easily resolved.


Anyway, if it will make anyone's life simpler, I've specified an MIT license.

**Comment by Foxboron** [comment]
@kovetskiy Remember you also need to explicitly state that you agree with the chosen license (MIT) for your code contributions. You can also pick a compatible license if you don't agree with it.

**Comment by noerw** [comment]
Thanks for clarifying @seletskiy. I meant to follow up, but lost track of this myself.
Meanwhile it's a bit ..special that the author of that blog made a lot of noise without talking to either of us directly, but it is how it is 🙃
The license addition is adopted downstream [here](https://gitea.com/noerw/unidiff-comments/commit/c70f49287e75f66e474f107359b0ab77b9df5f3d) and [here](https://gitea.com/gitea/tea/issues/493).

**Comment by MTecknology** [comment]
For what it's worth, this is just one of many identical problems within gitea.
enjoy some snark from the past: https://github.com/go-gitea/debian-packaging/blob/master/debian/copyright#L31
